import localFont from "next/font/local";
import "./globals.css";
import SliderTop from "./Commen/SliderTop";
import Header from "./Commen/Header";
import Footer from "./Commen/Footer";



export const metadata = {
  title: "Frank And Oak USA",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
       
        {children}
        
      </body>
    </html>
  );
}
